
[versions]
commons-math3 = "3.6.1"
fresco = "3.6.0"
guava = "33.5.0-jre"
agp = "8.13.0"
kotlin = "2.2.21"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.9.4"
activityCompose = "1.11.0"
composeBom = "2025.10.01"
constraintlayout = "2.2.1"
appcompat = "1.7.1"
lynx = "3.4.2"
lynxJssdk = "3.4.2"
lynxServiceHttp = "3.4.2"
lynxServiceImage = "3.4.2"
lynxServiceLog = "3.4.2"
lynxTrace = "3.4.2"
lynxpo = "1.0.24"
okhttp = "5.3.0"
primjs = "2.14.1"

[libraries]
animated-base = { module = "com.facebook.fresco:animated-base", version.ref = "fresco" }
animated-gif = { module = "com.facebook.fresco:animated-gif", version.ref = "fresco" }
animated-webp = { module = "com.facebook.fresco:animated-webp", version.ref = "fresco" }
commons-math3 = { module = "org.apache.commons:commons-math3", version.ref = "commons-math3" }
fresco = { module = "com.facebook.fresco:fresco", version.ref = "fresco" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }

androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
lynx = { module = "org.lynxsdk.lynx:lynx", version.ref = "lynx" }
lynx-jssdk = { module = "org.lynxsdk.lynx:lynx-jssdk", version.ref = "lynxJssdk" }
lynx-service-http = { module = "org.lynxsdk.lynx:lynx-service-http", version.ref = "lynxServiceHttp" }
lynx-service-image = { module = "org.lynxsdk.lynx:lynx-service-image", version.ref = "lynxServiceImage" }
lynx-service-log = { module = "org.lynxsdk.lynx:lynx-service-log", version.ref = "lynxServiceLog" }
lynx-trace = { module = "org.lynxsdk.lynx:lynx-trace", version.ref = "lynxTrace" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
primjs = { module = "org.lynxsdk.lynx:primjs", version.ref = "primjs" }
webpsupport = { module = "com.facebook.fresco:webpsupport", version.ref = "fresco" }
lynxpo = { module = "lynxpo.core:core", version.ref = "lynxpo" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
